AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Terraform to deploy Transit Gateway, VPC, and IPAM resources

Parameters:
  AutomationAccountId:
    Type: String
    Description: The AWS Account ID of the automation/CI/CD system that will assume this role

Resources:
  TerraformDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DEVTerraformDeploymentRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AutomationAccountId}:root
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: TerraformDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: IPAMPermissions
                Effect: Allow
                Action:
                  - ec2:CreateIpam
                  - ec2:DeleteIpam
                  - ec2:ModifyIpam
                  - ec2:DescribeIpams
                  - ec2:CreateIpamPool
                  - ec2:DeleteIpamPool
                  - ec2:ModifyIpamPool
                  - ec2:DescribeIpamPools
                  - ec2:CreateIpamScope
                  - ec2:DeleteIpamScope
                  - ec2:ModifyIpamScope
                  - ec2:DescribeIpamScopes
                  - ec2:AllocateIpamPoolCidr
                  - ec2:ReleaseIpamPoolCidr
                  - ec2:ProvisionIpamPoolCidr
                  - ec2:DeprovisionIpamPoolCidr
                  - ec2:GetIpamPoolCidrs
                  - ec2:GetIpamPoolAllocations
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - ec2:DescribeVpcAttribute
                  - ec2:CreateVpcEndpoint
                  - ec2:ReplaceNetworkAclAssociation
                  - ec2:DescribeSecurityGroupRules
                  - ec2:ReplaceNetworkAclAssociation
                  - ec2:DescribePrefixLists
                  - ec2:DescribeVpcEndpoints
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteVpcEndpoints
                Resource: '*'

              - Sid: RAMIPAMSharing
                Effect: Allow
                Action:
                  - ram:*
                  - ec2:DisassociateIpamResourceDiscovery
                  - ec2:AssociateIpamResourceDiscovery
                  - ec2:CreateIpamResourceDiscovery
                  - ec2:DeleteIpamResourceDiscovery
                  - ec2:GetIpamResourceCidrs
                  - ec2:ModifyIpamResourceCidr
                  - organizations:EnableAWSServiceAccess
                  - organizations:DescribeOrganization
                  - organizations:ListAccounts
                Resource: '*'

              - Sid: RAMResourceSharing
                Effect: Allow
                Action:
                  - ram:CreateResourceShare
                  - ram:DeleteResourceShare
                  - ram:UpdateResourceShare
                  - ram:AssociateResourceShare
                  - ram:DisassociateResourceShare
                  - ram:EnableSharingWithAwsOrganization
                  - ram:GetResourceShares
                  - ram:GetResourceShareAssociations
                  - ram:ListPendingInvitationResources
                  - ram:AcceptResourceShareInvitation
                  - ram:RejectResourceShareInvitation
                Resource: '*'

              - Sid: RAMIPAMResourceAssociation
                Effect: Allow
                Action:
                  - ram:AssociateResourceShare
                  - ram:DisassociateResourceShare
                  - ram:GetResourceShareAssociations
                  - ram:ListResources
                  - ram:PromoteResourceShareCreatedFromPolicy
                  - ram:EnableSharingWithAwsOrganization
                  - ram:CreateResourceShare
                  - ram:DeleteResourceShare
                  - ram:UpdateResourceShare
                  - ram:TagResource
                  - ram:UntagResource
                Resource:
                  - "arn:aws:ram:*:*:resource-share/*"
                  - "arn:aws:ec2:*:*:ipam-pool/*"
                  - "arn:aws:ram:*:*:permission/*"

              - Sid: OrganizationsAccess
                Effect: Allow
                Action:
                  - organizations:DescribeOrganization
                  - organizations:ListAccounts
                  - organizations:ListRoots
                  - organizations:ListOrganizationalUnitsForParent
                  - organizations:ListDelegatedServicesForAccount
                Resource: "*"

              - Sid: IPAMPoolManagement
                Effect: Allow
                Action:
                  - ec2:CreateIpamPool
                  - ec2:DeleteIpamPool
                  - ec2:GetIpamPoolAllocations
                  - ec2:ModifyIpamPool
                  - ec2:DescribeIpamPools
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: 
                  - "arn:aws:ec2:*:*:ipam-pool/*"
                  - "arn:aws:ec2:*:*:ipam/*"

              - Sid: TransitGatewayPermissions
                Effect: Allow
                Action:
                  - ec2:CreateTransitGateway
                  - ec2:CreateTransitGatewayRouteTable
                  - ec2:CreateTransitGatewayVpcAttachment
                  - ec2:AssociateTransitGatewayRouteTable
                  - ec2:EnableTransitGatewayRouteTablePropagation
                  - ec2:DeleteTransitGateway*
                  - ec2:DescribeTransitGateways
                  - ec2:DescribeTransitGateway*
                Resource: '*'

              - Sid: VpcNetworking
                Effect: Allow
                Action:
                  - ec2:CreateVpc
                  - ec2:DeleteVpc
                  - ec2:DescribeVpcs
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateSubnet
                  - ec2:DeleteSubnet
                  - ec2:DescribeSubnets
                  - ec2:CreateRouteTable
                  - ec2:AssociateRouteTable
                  - ec2:CreateRoute
                  - ec2:ReplaceRoute
                  - ec2:DeleteRoute
                  - ec2:DeleteRouteTable
                  - ec2:DescribeRouteTables
                  - ec2:CreateInternetGateway
                  - ec2:AttachInternetGateway
                  - ec2:DeleteInternetGateway
                  - ec2:DescribeInternetGateways
                  - ec2:CreateNatGateway
                  - ec2:DeleteNatGateway
                  - ec2:DisassociateRouteTable 
                  - ec2:DescribeNatGateways
                Resource: '*'

              - Sid: SecurityGroupsAndNetworking
                Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:DeleteSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ec2:CreateNetworkAcl
                  - ec2:DeleteNetworkAcl
                  - ec2:DescribeNetworkAcls
                  - ec2:CreateNetworkAclEntry
                  - ec2:DeleteNetworkAclEntry
                  - ec2:DescribeTags
                Resource: '*'

              - Sid: ElasticIPAndNatGateway
                Effect: Allow
                Action:
                  - ec2:AllocateAddress
                  - ec2:ReleaseAddress
                  - ec2:DescribeAddresses
                  - ec2:AssociateAddress
                  - ec2:DisassociateAddress
                Resource: '*'

              - Sid: Tagging
                Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                  - tag:GetResources
                  - tag:TagResources
                  - tag:UntagResources
                Resource: '*'

              - Sid: FlowLogs
                Effect: Allow
                Action:
                  - ec2:CreateFlowLogs
                  - ec2:DeleteFlowLogs
                  - ec2:DescribeFlowLogs
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:TagResource
                  - logs:ListTagsForResource
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                Resource: '*'

              - Sid: IAMForFlowLogs
                Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:TagRole
                  - iam:ListRolePolicies
                  - iam:GetRolePolicy
                  - iam:ListAttachedRolePolicies
                  - iam:ListInstanceProfilesForRole
                  - iam:PassRole
                Resource: '*'
              - Sid: RAMAdditionalPermissions
                Effect: Allow
                Action:
                  - ram:*
                  - ec2:*Ipam*
                  - organizations:*
                Resource: '*'

Outputs:
  RoleName:
    Value: !Ref TerraformDeploymentRole
    Description: Name of the IAM role created
  RoleArn:
    Value: !GetAtt TerraformDeploymentRole.Arn
    Description: ARN of the IAM role
